spring:
  application:
    name: superblog-api

  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password: SuperP4ssw0rd!
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate.ddl-auto: none
    generate-ddl: false
    properties.hibernate.jdbc.time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

  security:
    user:
      name: "admin"
      password: "admin"
    oauth2:
      authorization-server:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
              require-authorization-consent: true

app:
  base-path: "/api/v1"
  security:
    basic.enabled: false
    oauth2.enabled: true